- hosts: all

  hosts: localhost
  connection: local

  tasks:
    - name: add repos
      include: tasks/repos.yml

    - name: install base packages
      include: tasks/base_packages.yml

    - name: home layout
      include: tasks/home_layout.yml