---
- name: install and configure basic development stack

  block:

    - name: check if igv executable is present
      shell: "/usr/local/bin/igv"
      register: igv_bin
      ignore_errors: true



    - name: download IGV
      get_url:
        url: https://data.broadinstitute.org/igv/projects/downloads/2.11/IGV_Linux_2.11.0_WithJava.zip
        dest: /tmp/igv.zip
      when: igv_bin.rc != 0


    - name: Extract igv into /usr/local/lib/
      ansible.builtin.unarchive:
        src: /tmp/igv.tgz
        dest: /usr/local/lib/
      when: igv_bin.rc != 0


    - name: Create a symbolic link
      ansible.builtin.file:
        src: "{{item}}"
        dest: /usr/local/bin/igv
        state: link
      with_fileglob:
        - "/usr/local/lib/*/igv.sh"
      when: igv_bin.rc != 0


    - name: check if samtools executable is present
      shell: "/usr/local/bin/samtools"
      register: samtools_bin
      ignore_errors: true


    - name: Install samtools
      ansible.builtin.shell: 
        curl -Lo /tmp/samtools.tgz.bz2 https://github.com/samtools/samtools/releases/download/1.13/samtools-1.13.tar.bz2 
        mkdir /tmp/samtools 
        tar jxvf /tmp/samtools.tgz.bz2 --strip 1 -C /tmp/samtools 
        cd /tmp/samtools 
        ./configure --prefix=/usr/local/  
        make  
        make install  
        rm -rf /tmp/samtools*
      when: samtools_bin.rc != 0



