---
- name: download and install personal config files

  block:

    - name: clone git repository
    git:
      repo: git@github.com:bruggerk/config_files.git
      dest: /home/{{user_name}}/software
      force: yes
 

    - name: rename tmp ssh-dir so avoid clashes
      command:
        chdir: /home/{{user_name}}/
        cmd: mv .ssh .ssh_backup

    - name: make symbolic links
      command:
        cmd: sh make_links.sh
        chdir: /home/{{user_name}}/software/config_files

        
