---
- name: download and install personal config files

  block:

    - name: Ansible check file exists example.
      stat:
        path: /home/{{user_name}}/software/config_files
      register: config_files



    - name: clone config-files git repository
      git:
        repo: git@github.com:bruggerk/config_files.git
        dest: /home/{{user_name}}/software/config_files
      when: not config_files.stat.isdir

    - name: rename tmp ssh-dir so avoid clashes
      command:
        chdir: /home/{{user_name}}/
        cmd: mv .ssh .ssh_backup
      when: not config_files.stat.isdir

    - name: make symbolic links
      command:
        cmd: sh make_links.sh
        chdir: /home/{{user_name}}/software/config_files
      when: not config_files.stat.isdir


