---
- name: install and configure basic development stack

  block:

    - name: install packages
      package:
        name:
        - postgresql-client
        - postgresql-12
        - mariadb-client
        - mariadb-server

    - name: install microsoft packages
      package:
        name:
        - code 
        - azure-cli

    - name: install google packages
      package:
        name:
        - google-chrome-stable


    - name: install docker packages
      package:
        name:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io


    - name: Ensure docker group exists
      ansible.builtin.group:
        name: docker
        state: present


    - name: adding user brugger to group docker
      user:
        name: brugger
        groups: docker
        append: yes

    - name: install rabbitmq-server packages
      package:
        name:
        - rabbitmq-server

    - name: start rabbitmq
      service:
        name: rabbitmq-server
        state: restarted

    - name: check if influx executable is present
      shell: "which influx"
      register: influx_bin
      ignore_errors: true

    - name: install influx2 
      apt:
        deb: https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.8-amd64.deb
      when: influx_bin.rc != 0
        

    - name: check if influx executable is present
      shell: "which telegraf"
      register: telegraf_bin
      ignore_errors: true

    - name: install telegraf
      apt:
        deb: https://dl.influxdata.com/telegraf/releases/telegraf_1.19.3-1_amd64.deb
      when: telegraf_bin.rc != 0



    - name: start influxdb
      service:
        name: influxdb
        state: restarted
      when: influx_bin.rc != 0

    - name: check if go executable is present
      shell: "/usr/local/go/bin/go version"
      register: go_bin
      ignore_errors: true

    - name: install go-lang
      include: go_lang.yml
      when: go_bin.rc != 0

    - name: check if singularity executable is present
      shell: "which singularity"
      register: singularity_bin
      ignore_errors: true

    - name: install singularity
      include: singularity.yml
      when: singularity_bin.rc != 0

