---
- name: Homedir layout

  block:

    - name: make default dirs in home
      ansible.builtin.file:
        path: "/home/brugger/{{item}}"
        state: directory
        owner: brugger
      loop:
        - bin
        - tmp
        - projects
        - software


