---
- name: Homedir layout

  block:

    - name: make default dirs in home
      ansible.builtin.file:
        path: "/home/brugger/{{item}}"
        state: directory
        owner: brugger
      loop:
        - bin
        - tmp
        - projects
        - projects/kbr/
        - projects/nsm/
        - projects/misc/
        - software
        - .ssh



    - name: make .ssh dirs in home
      ansible.builtin.file:
        path: "/home/brugger/.ssh"
        state: directory
        owner: brugger
        mode: 0600


