- name: Add microsoft signing key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present


- name: Visual Studio Code repository
  ansible.builtin.apt_repository:
    repo: https://packages.microsoft.com/repos/code stable main
    state: present

- name: Visual Studio Code repository
  ansible.builtin.apt_repository:
    repo: https://packages.microsoft.com/yumrepos/azure-cli stable main
    state: present


