---
- name: add some non-standard repos

  block:

    - name: Add microsoft signing key
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
    
    - name: Visual Studio Code repository
      ansible.builtin.apt_repository:
        repo: deb https://packages.microsoft.com/repos/code stable main
        state: present
    
    - name: Azure-cli repository
      ansible.builtin.apt_repository:
        repo: deb https://packages.microsoft.com/repos/azure-cli focal main
        state: present
    
    
